from __future__ import annotations

from pathlib import Path

BOOK_YAML = """title: My Book
author: Your Name
language: en
description: A short tagline for your ebook.
publisher: Ebook Factory

chapters:
  - title: Introduction
    file: chapters/01-introduction.md
  - title: Getting Started
    file: chapters/02-getting-started.md
  - title: Conclusion
    file: chapters/03-conclusion.md
"""

CHAPTER_01 = """# Introduction

Welcome to your new ebook. This chapter was generated by **Ebook Factory**.

Edit `book.yaml` to set metadata, then add Markdown files under `chapters/`.
"""

CHAPTER_02 = """# Getting Started

## Write in Markdown

Use headings, lists, and code blocks as usual:

```python
from ebook_factory.factory import build_from_manifest
from pathlib import Path

build_from_manifest(Path("book.yaml"))
```

## Build your EPUB

```bash
ebook-factory build .
```
"""

CHAPTER_03 = """# Conclusion

You now have a repeatable pipeline from manuscript to EPUB.

Happy publishing!
"""


def scaffold_book(target: Path) -> Path:
    """Create a new book project directory with starter files."""
    target = target.resolve()
    if target.exists() and any(target.iterdir()):
        raise FileExistsError(f"Directory not empty: {target}")

    chapters = target / "chapters"
    dist = target / "dist"
    chapters.mkdir(parents=True)
    dist.mkdir(parents=True)

    (target / "book.yaml").write_text(BOOK_YAML, encoding="utf-8")
    (chapters / "01-introduction.md").write_text(CHAPTER_01, encoding="utf-8")
    (chapters / "02-getting-started.md").write_text(CHAPTER_02, encoding="utf-8")
    (chapters / "03-conclusion.md").write_text(CHAPTER_03, encoding="utf-8")

    return target
